/* =========================================================
   RUBROS — una plantilla por categoría.
   Contenido de arranque real: guaraníes, WhatsApp, horarios
   de siesta, facturación a RUC, envíos al interior.
   ========================================================= */
const RUBROS = [
{
  id:'gastronomia', rubro:'Gastronomía', sub:'Restaurante · Parrillada · Comedor', ini:'Ga',
  secciones:['nav','heroBanner','tiras','precios','texto','testimonios','contacto','pie'],
  d:{
    _accent:'#B3341F', _bg:'#FAF6F0', _fg:'#1E1713', _font:'editorial', _cardStyle:'grid',
    marca:'Parrilla Ykuá', navCta:'Reservar mesa',
    navLinks:[{txt:'Menú',url:'#precios'},{txt:'Nosotros',url:'#nosotros'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Asado a la estaca desde 1998',
    heroTitulo:'Carne al fuego, mandioca caliente y mesa larga',
    heroTexto:'Cocinamos a leña todos los días. Almuerzo ejecutivo de lunes a viernes, asado completo los fines de semana y delivery en todo el Gran Asunción.',
    heroCta:'Ver el menú', heroCtaUrl:'#precios', heroImg:'',
    tiras:[{valor:'27 años',etiqueta:'En el mismo barrio'},{valor:'Gs. 45.000',etiqueta:'Almuerzo ejecutivo'},
           {valor:'11:00 a 15:00',etiqueta:'Cocina abierta al mediodía'},{valor:'Delivery',etiqueta:'Asunción y alrededores'}],
    preciosTitulo:'Nuestro menú',
    preciosIntro:'Precios con IVA incluido. Facturamos a tu RUC en el momento.',
    precios:[
      {seccion:'Para empezar',nombre:'Chipa guasu',detalle:'Porción individual, horno de barro',precio:'Gs. 18.000'},
      {seccion:'Para empezar',nombre:'Empanadas de carne',detalle:'Media docena, fritas al momento',precio:'Gs. 30.000'},
      {seccion:'Para empezar',nombre:'Sopa paraguaya',detalle:'Porción generosa, receta de la casa',precio:'Gs. 15.000'},
      {seccion:'A la parrilla',nombre:'Asado de tira',detalle:'400 g con mandioca y ensalada',precio:'Gs. 72.000'},
      {seccion:'A la parrilla',nombre:'Vacío a la estaca',detalle:'Corte del día, mínimo 2 personas',precio:'Gs. 135.000'},
      {seccion:'A la parrilla',nombre:'Pollo al disco',detalle:'Con verduras salteadas',precio:'Gs. 58.000'},
      {seccion:'Postres y bebidas',nombre:'Dulce de mamón con queso Paraguay',detalle:'Casero',precio:'Gs. 16.000'},
      {seccion:'Postres y bebidas',nombre:'Jarra de mosto',detalle:'1 litro, bien frío',precio:'Gs. 20.000'}],
    textoTitulo:'Tres generaciones en la misma parrilla',
    textoCuerpo:'Empezamos en 1998 con seis mesas y una parrilla que mi papá armó con hierro de la chatarrería de la esquina. Hoy tenemos treinta mesas y la misma parrilla.\n\nLa carne la traemos de un frigorífico de Concepción, la mandioca del mercado de Abasto y el queso Paraguay de una quesería de Caacupé que nos vende desde el primer día.',
    textoImg:'',
    testiTitulo:'Lo que dicen los que vuelven',
    testimonios:[
      {texto:'El mejor vacío de la zona y te lo sirven en veinte minutos. Voy todos los viernes con los compañeros del trabajo.',autor:'Rodrigo A., cliente desde 2014'},
      {texto:'Pedimos para un cumpleaños de 40 personas y llegó todo caliente y a horario. Impecable.',autor:'Familia Ramírez, Fernando de la Mora'}],
    contactoTitulo:'Vení o pedí delivery',
    contactoTexto:'Reservas por WhatsApp hasta las 18:00. Para grupos de más de 10 personas, avisanos con un día de anticipación.',
    whatsapp:'0981 234 567', telefono:'021 555 123',
    direccion:'Av. Mcal. López 2340 c/ Rca. Argentina', ciudad:'Asunción',
    horario:'Lun a vie 11:00–15:00 y 19:00–23:00 · Sáb y dom 11:00–23:00',
    instagram:'parrillaykua', email:'reservas@parrillaykua.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Av.+Mcal.+Lopez+2340+Asuncion',
    pago:'Efectivo, tarjetas, Tigo Money, Billetera Personal y Zimple',
  }
},
{
  id:'moda', rubro:'Moda y textil', sub:'Tienda de ropa · Boutique', ini:'Mo',
  secciones:['nav','heroSplit','cards','texto','tiras','contacto','pie'],
  d:{
    _accent:'#43306B', _bg:'#F4F1EC', _fg:'#151217', _font:'moderna', _cardStyle:'grid',
    marca:'Tacuara', navCta:'Comprar por WhatsApp',
    navLinks:[{txt:'Colección',url:'#catalogo'},{txt:'La marca',url:'#nosotros'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Colección Primavera 2026',
    heroTitulo:'Ropa hecha acá, pensada para el calor de acá',
    heroTexto:'Lino, algodón y telas livianas cortadas en nuestro taller de Luque. Talles del 36 al 52, sin recargo. Envíos a todo el país por Encomiendas.',
    heroCta:'Ver la colección', heroCtaUrl:'#catalogo', heroImg:'',
    cardsTitulo:'Colección Primavera 2026',
    cardsIntro:'Todas las prendas se pueden pagar hasta en 3 cuotas sin interés con tarjeta.',
    cards:[
      {titulo:'Camisa Ykuá',meta:'Gs. 285.000',texto:'Lino lavado, corte amplio, botones de tagua. Talles 36 al 52.',img:''},
      {titulo:'Pantalón Takuare',meta:'Gs. 340.000',texto:'Algodón pesado de tiro alto con pinzas y bolsillo lateral.',img:''},
      {titulo:'Vestido Aramí',meta:'Gs. 395.000',texto:'Lino con ao po’i en el escote, bordado a mano en Yataity.',img:''},
      {titulo:'Saco Guaraní',meta:'Gs. 520.000',texto:'Doble faz sin forro, se usa de los dos lados.',img:''},
      {titulo:'Blusa Panambi',meta:'Gs. 215.000',texto:'Algodón liviano, manga tres cuartos.',img:''},
      {titulo:'Falda Yvoty',meta:'Gs. 260.000',texto:'Midi con tablas, cae sin planchar.',img:''}],
    textoTitulo:'Taller propio en Luque',
    textoCuerpo:'No tercerizamos. Cortamos, cosemos y terminamos todo en un taller de nueve personas, con sueldo en blanco y horario fijo.\n\nEl bordado ao po’i lo hacen tres bordadoras de Yataity que trabajan con nosotros desde 2019. Cada prenda bordada lleva el nombre de quien la bordó en la etiqueta.',
    textoImg:'',
    tiras:[{valor:'36 al 52',etiqueta:'Talles sin recargo'},{valor:'3 cuotas',etiqueta:'Sin interés con tarjeta'},
           {valor:'24 a 72 h',etiqueta:'Envío al interior'},{valor:'9 personas',etiqueta:'En el taller de Luque'}],
    contactoTitulo:'Probate antes de comprar',
    contactoTexto:'Atendemos en el showroom con cita previa. Mandanos tus medidas por WhatsApp y te decimos qué talle te queda.',
    whatsapp:'0971 445 880', telefono:'',
    direccion:'Av. Aviadores del Chaco 1580, piso 2', ciudad:'Asunción',
    horario:'Lun a vie 10:00–18:00 · Sáb 10:00–13:00',
    instagram:'tacuara.py', email:'hola@tacuara.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Aviadores+del+Chaco+1580+Asuncion',
    pago:'Tarjetas, transferencia bancaria, Tigo Money y Zimple',
  }
},
{
  id:'belleza', rubro:'Belleza', sub:'Barbería · Peluquería · Estética', ini:'Be',
  secciones:['nav','heroTipo','precios','pasos','texto','contacto','pie'],
  d:{
    _accent:'#8A5C2E', _bg:'#F8F2EA', _fg:'#1E1813', _font:'editorial', _cardStyle:'grid',
    marca:'Barbería Che Róga', navCta:'Agendar turno',
    navLinks:[{txt:'Servicios',url:'#precios'},{txt:'Nosotros',url:'#nosotros'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Barbería y estética · San Lorenzo',
    heroTitulo:'Turno a la hora que pediste. Sin espera.',
    heroTexto:'Corte, barba, color y tratamientos con reserva por WhatsApp. Cuatro sillas, cuatro barberos, y el mate siempre listo.',
    heroCta:'Ver servicios y precios', heroCtaUrl:'#precios', heroImg:'',
    preciosTitulo:'Servicios y precios',
    preciosIntro:'Sin sobreprecio los fines de semana. El turno se confirma por WhatsApp.',
    precios:[
      {seccion:'Cabello',nombre:'Corte clásico',detalle:'Lavado, corte y peinado · 40 min',precio:'Gs. 55.000'},
      {seccion:'Cabello',nombre:'Corte + barba',detalle:'Con toalla caliente · 60 min',precio:'Gs. 85.000'},
      {seccion:'Cabello',nombre:'Corte niño',detalle:'Hasta 12 años · 30 min',precio:'Gs. 40.000'},
      {seccion:'Barba',nombre:'Perfilado de barba',detalle:'Navaja y aceite · 25 min',precio:'Gs. 45.000'},
      {seccion:'Barba',nombre:'Afeitado completo',detalle:'Ritual con toalla caliente · 35 min',precio:'Gs. 60.000'},
      {seccion:'Color y tratamientos',nombre:'Color / cobertura de canas',detalle:'Según largo · 60 a 90 min',precio:'desde Gs. 120.000'},
      {seccion:'Color y tratamientos',nombre:'Hidratación capilar',detalle:'Con masaje · 30 min',precio:'Gs. 75.000'}],
    pasosTitulo:'Cómo reservar',
    pasos:[
      {titulo:'Escribinos',texto:'Mandá un WhatsApp con el servicio que querés y dos horarios que te sirvan.'},
      {titulo:'Te confirmamos',texto:'En menos de una hora te decimos el turno exacto y con qué barbero.'},
      {titulo:'Venís y listo',texto:'Llegá cinco minutos antes. Si no podés venir, avisá con dos horas de anticipación.'}],
    textoTitulo:'Once años cortando en el mismo lugar',
    textoCuerpo:'Abrimos en 2015 en una pieza alquilada sobre la Ruta Mcal. Estigarribia. Hoy somos cuatro barberos y una esteticista, y seguimos a media cuadra de donde empezamos.\n\nTrabajamos con turno para que nadie pierda la tarde esperando. Si llegás sin reserva te atendemos igual, pero puede que tengas que esperar.',
    textoImg:'',
    contactoTitulo:'Pedí tu turno',
    contactoTexto:'Respondemos de 8:00 a 20:00. Los domingos estamos cerrados.',
    whatsapp:'0985 112 334', telefono:'021 574 908',
    direccion:'Ruta Mcal. Estigarribia km 12,5', ciudad:'San Lorenzo',
    horario:'Mar a sáb 8:00–20:00 · Lun 13:00–20:00 · Dom cerrado',
    instagram:'cheroga.barberia', email:'',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Ruta+Mariscal+Estigarribia+km+12.5+San+Lorenzo',
    pago:'Efectivo, tarjetas, Tigo Money y Billetera Personal',
  }
},
{
  id:'inmobiliaria', rubro:'Inmobiliaria', sub:'Venta · Alquiler · Loteamientos', ini:'In',
  secciones:['nav','heroSplit','tiras','cards','pasos','faq','contacto','pie'],
  d:{
    _accent:'#14567F', _bg:'#F3F6F8', _fg:'#101A21', _font:'tecnica', _cardStyle:'ancho',
    marca:'Inmobiliaria Paraná', navCta:'Consultar',
    navLinks:[{txt:'Propiedades',url:'#catalogo'},{txt:'Preguntas',url:'#preguntas'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Matrícula SENAVITAT 4417',
    heroTitulo:'Casas, departamentos y terrenos con papeles al día',
    heroTexto:'Operamos en Asunción, Luque, San Bernardino y Encarnación. Verificamos título, catastro y deudas antes de publicar cualquier propiedad.',
    heroCta:'Ver propiedades', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'18 años',etiqueta:'En el mercado'},{valor:'240+',etiqueta:'Operaciones cerradas'},
           {valor:'100%',etiqueta:'Con título verificado'},{valor:'4 ciudades',etiqueta:'Zona de cobertura'}],
    cardsTitulo:'Propiedades disponibles',
    cardsIntro:'Actualizamos la lista todos los lunes. Si no ves lo que buscás, escribinos: tenemos cartera no publicada.',
    cards:[
      {titulo:'Casa 3 dormitorios — Luque, Laurelty',meta:'USD 95.000 · 210 m² terreno',
       texto:'Dos baños, quincho con parrilla, cochera para dos autos. Título propio, libre de deuda. Apta crédito AFD.',img:''},
      {titulo:'Departamento 2 dormitorios — Villa Morra',meta:'USD 850/mes · 78 m²',
       texto:'Piso 8 con balcón, amoblado, gimnasio y piscina en el edificio. Expensas Gs. 950.000.',img:''},
      {titulo:'Terreno 12 x 30 — San Bernardino',meta:'Gs. 320.000.000 · 360 m²',
       texto:'A cuatro cuadras del lago, calle empedrada, agua y luz en el frente. Se acepta financiación en 24 cuotas.',img:''},
      {titulo:'Local comercial — Encarnación, centro',meta:'Gs. 4.500.000/mes · 95 m²',
       texto:'Sobre avenida, vidriera a la calle, baño y depósito. Ideal comercio o consultorio.',img:''}],
    pasosTitulo:'Cómo es comprar con nosotros',
    pasos:[
      {titulo:'Visita',texto:'Coordinamos la visita en el horario que te sirva, incluso sábados por la mañana.'},
      {titulo:'Verificación',texto:'Sacamos el informe de Dirección de Registros Públicos y el certificado catastral.'},
      {titulo:'Reserva',texto:'Se firma boleto de reserva con seña. Si algo del informe no cierra, se devuelve íntegra.'},
      {titulo:'Escritura',texto:'Escribana de tu confianza o de la casa. Acompañamos hasta la inscripción del título.'}],
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿Cobran comisión al comprador?',r:'No. La comisión la paga quien vende: 5% sobre el valor de la operación, como marca la práctica del mercado.'},
      {p:'¿Trabajan con crédito de la AFD?',r:'Sí. Varias de nuestras propiedades están aprobadas para crédito de la Agencia Financiera de Desarrollo. Te ayudamos a armar la carpeta.'},
      {p:'¿Qué necesito para alquilar?',r:'Cédula, comprobante de ingresos de los últimos tres meses y un garante propietario. El depósito es de un mes.'}],
    contactoTitulo:'Hablemos de lo que buscás',
    contactoTexto:'Contanos zona, presupuesto y para cuándo lo necesitás. Te mandamos opciones el mismo día.',
    whatsapp:'0961 700 214', telefono:'021 604 330',
    direccion:'Av. España 1245, oficina 3', ciudad:'Asunción',
    horario:'Lun a vie 8:00–12:00 y 14:00–18:00 · Sáb 8:00–12:00',
    instagram:'inmobiliariaparana', email:'contacto@inmoparana.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Avenida+Espana+1245+Asuncion',
    pago:'Transferencia bancaria y cheque. Operaciones en guaraníes o dólares.',
  }
},
{
  id:'agro', rubro:'Agro y ganadería', sub:'Insumos · Campos · Servicios rurales', ini:'Ag',
  secciones:['nav','heroBanner','tiras','cards','texto','faq','contacto','pie'],
  d:{
    _accent:'#2E6B30', _bg:'#F4F7EF', _fg:'#131A12', _font:'tecnica', _cardStyle:'grid',
    marca:'Agro Yvoty', navCta:'Pedir cotización',
    navLinks:[{txt:'Productos',url:'#catalogo'},{txt:'Nosotros',url:'#nosotros'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Itapúa · Alto Paraná · Canindeyú',
    heroTitulo:'Insumos, semillas y asistencia técnica a pie de chacra',
    heroTexto:'Atendemos productores de soja, maíz, trigo y ganadería desde 2009. Entrega en finca, financiación hasta la cosecha y un ingeniero agrónomo que va al lote.',
    heroCta:'Ver productos', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'17 años',etiqueta:'Acompañando zafras'},{valor:'3 departamentos',etiqueta:'Cobertura propia'},
           {valor:'48 h',etiqueta:'Entrega en finca'},{valor:'Canje',etiqueta:'Pago con granos'}],
    cardsTitulo:'Líneas que manejamos',
    cardsIntro:'Precios sujetos a cotización del día. Financiamos a cosecha con contrato de canje.',
    cards:[
      {titulo:'Semilla de soja',meta:'Variedades INTA y locales',texto:'Tratada y curada, con poder germinativo certificado. Bolsa de 40 kg.',img:''},
      {titulo:'Fertilizantes',meta:'Urea, fosfatados, mezclas',texto:'A granel o embolsado. Análisis de suelo gratuito para pedidos desde 20 toneladas.',img:''},
      {titulo:'Agroquímicos',meta:'Herbicidas, fungicidas, insecticidas',texto:'Productos registrados en SENAVE con receta agronómica incluida.',img:''},
      {titulo:'Sanidad animal',meta:'Vacunas y antiparasitarios',texto:'Cadena de frío controlada. Vacuna antiaftosa en campaña oficial.',img:''},
      {titulo:'Alambrados y postes',meta:'Postes de quebracho',texto:'Alambre liso, púa y boyero eléctrico. Entrega en tranquera.',img:''},
      {titulo:'Asistencia técnica',meta:'Sin costo para clientes',texto:'Visita de nuestro ingeniero agrónomo al lote: recomendación de dosis y monitoreo de plagas.',img:''}],
    textoTitulo:'Vamos al lote, no esperamos en el mostrador',
    textoCuerpo:'Somos tres socios: dos ingenieros agrónomos y un contador. Salimos a recorrer chacras cuatro días por semana, porque el problema de una soja no se diagnostica por teléfono.\n\nTrabajamos con canje: el productor retira insumos en la siembra y paga con granos en la cosecha, al precio pizarra del día de entrega. El contrato se firma antes, sin letra chica.',
    textoImg:'',
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿Cómo funciona el canje?',r:'Retirás los insumos que necesitás y firmás un contrato que fija cuántos kilos de grano vas a entregar en la cosecha. El precio se cierra el día de la entrega, con la pizarra oficial.'},
      {p:'¿Entregan en el interior?',r:'Sí. Entrega sin costo en Itapúa, Alto Paraná y Canindeyú para pedidos desde Gs. 15.000.000. Fuera de esa zona cotizamos el flete.'},
      {p:'¿Emiten factura para descargar IVA?',r:'Sí, facturamos a tu RUC en todas las operaciones, incluidas las de canje.'}],
    contactoTitulo:'Pedí tu cotización',
    contactoTexto:'Mandanos superficie, cultivo y fecha estimada de siembra. Te cotizamos el paquete completo en 24 horas.',
    whatsapp:'0985 640 110', telefono:'071 203 441',
    direccion:'Ruta PY06 km 38, Colonia Obligado', ciudad:'Itapúa',
    horario:'Lun a vie 7:00–11:30 y 13:30–17:30 · Sáb 7:00–12:00',
    instagram:'agroyvoty', email:'ventas@agroyvoty.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Colonia+Obligado+Itapua+Paraguay',
    pago:'Contado, cheque diferido, canje de granos y financiación a cosecha',
  }
},
];

RUBROS.push(
{
  id:'salud', rubro:'Salud', sub:'Consultorio médico · Odontología', ini:'Sa',
  secciones:['nav','heroSplit','tiras','precios','pasos','faq','contacto','pie'],
  d:{
    _accent:'#0E7A86', _bg:'#F2F8F8', _fg:'#0F1D1F', _font:'moderna', _cardStyle:'grid',
    marca:'Centro Odontológico Sonríe', navCta:'Agendar consulta',
    navLinks:[{txt:'Tratamientos',url:'#precios'},{txt:'Cómo agendar',url:'#preguntas'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Reg. Prof. 8842 · Ministerio de Salud Pública',
    heroTitulo:'Odontología sin sorpresas en el presupuesto',
    heroTexto:'Primera consulta con diagnóstico y plan de tratamiento escrito, con precio cerrado antes de empezar. Atendemos adultos y niños.',
    heroCta:'Ver tratamientos', heroCtaUrl:'#precios', heroImg:'',
    tiras:[{valor:'Gs. 80.000',etiqueta:'Primera consulta'},{valor:'6 cuotas',etiqueta:'Sin interés en tratamientos'},
           {valor:'Sábados',etiqueta:'Atendemos hasta las 13:00'},{valor:'Urgencias',etiqueta:'Mismo día, con turno'}],
    preciosTitulo:'Tratamientos y aranceles',
    preciosIntro:'Los valores son de referencia. El presupuesto definitivo se cierra en la primera consulta, por escrito.',
    precios:[
      {seccion:'Consultas',nombre:'Primera consulta y diagnóstico',detalle:'Incluye plan de tratamiento escrito',precio:'Gs. 80.000'},
      {seccion:'Consultas',nombre:'Urgencia por dolor',detalle:'Atención el mismo día',precio:'Gs. 120.000'},
      {seccion:'Prevención',nombre:'Limpieza y pulido',detalle:'Profilaxis completa · 45 min',precio:'Gs. 180.000'},
      {seccion:'Prevención',nombre:'Aplicación de flúor',detalle:'Recomendado en niños',precio:'Gs. 90.000'},
      {seccion:'Restauración',nombre:'Empaste de resina',detalle:'Por pieza, color según diente',precio:'desde Gs. 190.000'},
      {seccion:'Restauración',nombre:'Tratamiento de conducto',detalle:'Según cantidad de conductos',precio:'desde Gs. 750.000'},
      {seccion:'Estética',nombre:'Blanqueamiento en consultorio',detalle:'Dos sesiones',precio:'Gs. 1.200.000'},
      {seccion:'Estética',nombre:'Ortodoncia — colocación',detalle:'Brackets metálicos, ambas arcadas',precio:'Gs. 2.400.000'}],
    pasosTitulo:'Cómo agendar',
    pasos:[
      {titulo:'Escribinos',texto:'Por WhatsApp, contando qué te pasa y si tenés dolor. Las urgencias se priorizan.'},
      {titulo:'Elegís horario',texto:'Te ofrecemos tres turnos disponibles esa misma semana.'},
      {titulo:'Primera consulta',texto:'Revisión, radiografía si hace falta y presupuesto por escrito. No empezamos nada sin que lo apruebes.'},
      {titulo:'Tratamiento',texto:'Se agenda toda la serie de sesiones de una vez, para que no pierdas continuidad.'}],
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿Trabajan con seguro médico?',r:'Sí, con los principales prepagos del país. Traé tu carnet y verificamos la cobertura antes de la consulta.'},
      {p:'¿Se puede pagar en cuotas?',r:'Los tratamientos desde Gs. 1.000.000 se pueden pagar hasta en 6 cuotas sin interés con tarjeta de crédito.'},
      {p:'¿Atienden niños?',r:'Sí. Tenemos una odontopediatra que atiende martes y jueves por la tarde y los sábados por la mañana.'}],
    contactoTitulo:'Pedí tu turno',
    contactoTexto:'Respondemos en el día. Si tenés dolor, escribí “urgencia” al inicio del mensaje.',
    whatsapp:'0982 330 771', telefono:'021 227 450',
    direccion:'Dr. Hassler 3320 c/ Cruz del Chaco', ciudad:'Asunción',
    horario:'Lun a vie 8:00–12:00 y 14:00–19:00 · Sáb 8:00–13:00',
    instagram:'sonrie.consultorio', email:'turnos@sonrie.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Dr.+Hassler+3320+Asuncion',
    pago:'Efectivo, tarjetas, transferencia y seguros médicos',
  }
},
{
  id:'automotriz', rubro:'Automotriz', sub:'Taller mecánico · Repuestos', ini:'Au',
  secciones:['nav','heroBanner','tiras','precios','cards','pasos','contacto','pie'],
  d:{
    _accent:'#D2540F', _bg:'#14171A', _fg:'#E8ECEF', _font:'tecnica', _cardStyle:'compacto',
    marca:'Taller San Miguel', navCta:'Pedir presupuesto',
    navLinks:[{txt:'Servicios',url:'#precios'},{txt:'Repuestos',url:'#catalogo'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Mecánica general y repuestos · desde 2006',
    heroTitulo:'Te decimos el precio antes de tocar el auto',
    heroTexto:'Diagnóstico computarizado, service completo y repuestos originales y alternativos. Presupuesto por WhatsApp con foto del problema.',
    heroCta:'Ver servicios', heroCtaUrl:'#precios', heroImg:'',
    tiras:[{valor:'20 años',etiqueta:'En el rubro'},{valor:'6 meses',etiqueta:'Garantía de mano de obra'},
           {valor:'Scanner',etiqueta:'Diagnóstico computarizado'},{valor:'Mismo día',etiqueta:'Services programados'}],
    preciosTitulo:'Servicios del taller',
    preciosIntro:'Mano de obra. Los repuestos se cotizan aparte, y te mostramos el precio antes de comprarlos.',
    precios:[
      {seccion:'Mantenimiento',nombre:'Service completo',detalle:'Aceite, filtros de aire, aceite y habitáculo',precio:'desde Gs. 450.000'},
      {seccion:'Mantenimiento',nombre:'Cambio de correa de distribución',detalle:'Según modelo · 4 a 6 horas',precio:'desde Gs. 850.000'},
      {seccion:'Mantenimiento',nombre:'Alineación y balanceo',detalle:'Cuatro ruedas',precio:'Gs. 180.000'},
      {seccion:'Diagnóstico',nombre:'Escaneo computarizado',detalle:'Lectura y borrado de códigos · 40 min',precio:'Gs. 150.000'},
      {seccion:'Diagnóstico',nombre:'Revisión pre-compra',detalle:'Informe escrito de 30 puntos',precio:'Gs. 350.000'},
      {seccion:'Frenos y suspensión',nombre:'Cambio de pastillas',detalle:'Por tren, mano de obra',precio:'Gs. 200.000'},
      {seccion:'Frenos y suspensión',nombre:'Cambio de amortiguadores',detalle:'Por par, mano de obra',precio:'Gs. 320.000'},
      {seccion:'Aire acondicionado',nombre:'Carga de gas y prueba de fugas',detalle:'R134a',precio:'Gs. 280.000'}],
    cardsTitulo:'Repuestos que tenemos en stock',
    cardsIntro:'Si no lo tenemos, lo conseguimos en 48 a 72 horas desde Ciudad del Este.',
    cards:[
      {titulo:'Filtros',meta:'Aire, aceite, combustible',texto:'Para Toyota, Nissan, Kia, Hyundai, Chevrolet y Volkswagen.',img:''},
      {titulo:'Pastillas y discos',meta:'Original y alternativo',texto:'Marcas con garantía escrita de 20.000 km.',img:''},
      {titulo:'Baterías',meta:'Desde Gs. 650.000',texto:'12 meses de garantía. Instalación sin costo y retiramos la vieja.',img:''},
      {titulo:'Aceites y lubricantes',meta:'Sintético y semisintético',texto:'5W30, 10W40 y 15W40. Bidón o litro suelto.',img:''}],
    pasosTitulo:'Cómo trabajamos',
    pasos:[
      {titulo:'Mandás el problema',texto:'Por WhatsApp: modelo, año y un video del ruido o la falla si se puede.'},
      {titulo:'Diagnóstico',texto:'Traés el auto, lo escaneamos y revisamos. Te llamamos con el diagnóstico.'},
      {titulo:'Presupuesto cerrado',texto:'Te pasamos mano de obra y repuestos por separado. Recién ahí decidís.'},
      {titulo:'Entrega con garantía',texto:'Seis meses de garantía sobre la mano de obra, por escrito en la factura.'}],
    contactoTitulo:'Traé tu auto o escribinos',
    contactoTexto:'Para service programado conviene avisar con un día. Las urgencias las vemos en el momento.',
    whatsapp:'0971 208 553', telefono:'021 332 117',
    direccion:'Av. Fernando de la Mora 1890', ciudad:'Fernando de la Mora',
    horario:'Lun a vie 7:30–12:00 y 13:30–18:00 · Sáb 7:30–12:00',
    instagram:'tallersanmiguel.py', email:'',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Avenida+Fernando+de+la+Mora+1890',
    pago:'Efectivo, tarjetas, transferencia y Tigo Money',
  }
},
{
  id:'construccion', rubro:'Construcción', sub:'Constructora · Corralón de materiales', ini:'Co',
  secciones:['nav','heroSplit','tiras','cards','pasos','texto','faq','contacto','pie'],
  d:{
    _accent:'#A9610F', _bg:'#F6F2EB', _fg:'#191510', _font:'tecnica', _cardStyle:'ancho',
    marca:'Constructora Tape', navCta:'Pedir presupuesto',
    navLinks:[{txt:'Obras',url:'#catalogo'},{txt:'Proceso',url:'#nosotros'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Obra nueva, refacción y dirección técnica',
    heroTitulo:'Presupuesto cerrado y plazo firmado',
    heroTexto:'Construimos casas, locales y depósitos en Asunción y Gran Asunción. Planilla de cómputo abierta: ves cada material y cada jornal.',
    heroCta:'Ver obras', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'14 años',etiqueta:'Construyendo'},{valor:'62 obras',etiqueta:'Entregadas'},
           {valor:'Gs. 4,5 M',etiqueta:'Costo por m² desde'},{valor:'Plazo firmado',etiqueta:'Con multa por atraso'}],
    cardsTitulo:'Obras entregadas',
    cardsIntro:'Podemos coordinar una visita a obras terminadas para que hables directo con los propietarios.',
    cards:[
      {titulo:'Vivienda unifamiliar — Mariano Roque Alonso',meta:'180 m² · 9 meses',
       texto:'Tres dormitorios, quincho y piscina. Estructura de hormigón armado, techo de losa con aislación térmica.',img:''},
      {titulo:'Depósito logístico — Luque',meta:'900 m² · 7 meses',
       texto:'Nave con estructura metálica, piso de hormigón alisado de alta resistencia y oficina en entrepiso.',img:''},
      {titulo:'Refacción de local comercial — Asunción centro',meta:'95 m² · 6 semanas',
       texto:'Demolición, instalación eléctrica nueva, aire acondicionado y vidriera. Local abierto durante parte de la obra.',img:''}],
    pasosTitulo:'Cómo llegamos al precio',
    pasos:[
      {titulo:'Visita al terreno',texto:'Vamos al lugar, medimos y vemos accesos, nivel y servicios. Sin costo.'},
      {titulo:'Anteproyecto',texto:'Planta y vistas para que veas la casa antes de decidir. Se ajusta hasta que te cierre.'},
      {titulo:'Cómputo y presupuesto',texto:'Planilla abierta con cantidades, materiales y jornales. Nada de precio global sin detalle.'},
      {titulo:'Contrato y obra',texto:'Plazo, certificaciones mensuales y multa por atraso escritas en el contrato.'}],
    textoTitulo:'Planilla abierta, sin sorpresas al final',
    textoCuerpo:'La mayoría de los conflictos en obra empiezan por un presupuesto que no detalla nada. Nosotros entregamos el cómputo métrico completo: cuántas bolsas de cemento, cuántos metros de caño, cuántos jornales de albañil.\n\nSi durante la obra aparece un adicional, se firma por escrito antes de ejecutarlo. Nunca aparece en la factura final algo que no aprobaste.',
    textoImg:'',
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿Cuánto sale el metro cuadrado?',r:'Desde Gs. 4.500.000 por m² para terminación estándar y desde Gs. 6.200.000 para terminación premium. El valor final depende del terreno y del nivel de terminación.'},
      {p:'¿Hacen los planos y la aprobación municipal?',r:'Sí. Incluimos proyecto, memoria de cálculo, aprobación en la municipalidad y conexiones de ESSAP y ANDE.'},
      {p:'¿Qué pasa si se atrasan?',r:'El contrato fija una multa diaria a favor del propietario. Nos pasó dos veces en catorce años y la pagamos.'}],
    contactoTitulo:'Contanos qué querés construir',
    contactoTexto:'Mandanos ubicación del terreno, metros aproximados y para cuándo lo necesitás.',
    whatsapp:'0983 115 620', telefono:'021 719 044',
    direccion:'Av. Artigas 4120', ciudad:'Asunción',
    horario:'Lun a vie 7:00–17:00 · Sáb 7:00–12:00',
    instagram:'constructoratape', email:'obras@tape.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Avenida+Artigas+4120+Asuncion',
    pago:'Certificaciones mensuales por transferencia. Anticipo del 20%.',
  }
},
{
  id:'despensa', rubro:'Despensa y delivery', sub:'Minimercado · Almacén de barrio', ini:'De',
  secciones:['nav','heroBanner','tiras','cards','precios','pasos','contacto','pie'],
  d:{
    _accent:'#C22B30', _bg:'#FFFCF5', _fg:'#1B1512', _font:'moderna', _cardStyle:'compacto',
    marca:'Despensa Doña Ña', navCta:'Pedir por WhatsApp',
    navLinks:[{txt:'Combos',url:'#catalogo'},{txt:'Precios',url:'#precios'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Delivery en el barrio en 30 minutos',
    heroTitulo:'Hacés la lista, te la llevamos a la puerta',
    heroTexto:'Mandá tu lista por WhatsApp y te la llevamos el mismo día. Envío sin costo desde Gs. 100.000 en un radio de 15 cuadras.',
    heroCta:'Ver combos', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'30 min',etiqueta:'Tiempo de entrega'},{valor:'Gs. 100.000',etiqueta:'Envío gratis desde'},
           {valor:'7:00 a 21:00',etiqueta:'Todos los días'},{valor:'15 cuadras',etiqueta:'Radio de reparto'}],
    cardsTitulo:'Combos armados',
    cardsIntro:'Pedilos por nombre y ya sabemos qué preparar. También armamos combos a medida.',
    cards:[
      {titulo:'Combo Canasta',meta:'Gs. 185.000',texto:'Aceite 900 ml, arroz 1 kg, fideo 500 g, azúcar 1 kg, yerba 500 g, harina 1 kg y sal.',img:''},
      {titulo:'Combo Asado',meta:'Gs. 240.000',texto:'Carbón 3 kg, sal gruesa, mandioca 2 kg, tomate, cebolla, pan y hielo.',img:''},
      {titulo:'Combo Desayuno',meta:'Gs. 95.000',texto:'Leche 1 L, cocido en saquitos, pan casero, manteca y mermelada.',img:''},
      {titulo:'Combo Limpieza',meta:'Gs. 130.000',texto:'Detergente, lavandina, jabón en polvo 800 g, esponja y bolsas de basura.',img:''}],
    preciosTitulo:'Precios de referencia',
    preciosIntro:'Los básicos, actualizados cada lunes. El resto cotizamos por WhatsApp.',
    precios:[
      {seccion:'Almacén',nombre:'Aceite de soja 900 ml',detalle:'',precio:'Gs. 14.500'},
      {seccion:'Almacén',nombre:'Arroz 1 kg',detalle:'Tipo largo fino',precio:'Gs. 9.800'},
      {seccion:'Almacén',nombre:'Yerba mate 500 g',detalle:'Con palo',precio:'Gs. 16.000'},
      {seccion:'Almacén',nombre:'Azúcar 1 kg',detalle:'',precio:'Gs. 7.500'},
      {seccion:'Frescos',nombre:'Pan casero',detalle:'Por kilo, horneado a la mañana',precio:'Gs. 12.000'},
      {seccion:'Frescos',nombre:'Queso Paraguay',detalle:'Por kilo',precio:'Gs. 38.000'},
      {seccion:'Frescos',nombre:'Huevos',detalle:'Maple de 30',precio:'Gs. 32.000'},
      {seccion:'Bebidas',nombre:'Gaseosa 2 L',detalle:'Varios sabores',precio:'Gs. 12.000'},
      {seccion:'Bebidas',nombre:'Hielo 3 kg',detalle:'',precio:'Gs. 8.000'}],
    pasosTitulo:'Cómo pedir',
    pasos:[
      {titulo:'Mandá tu lista',texto:'Escrita o por audio, como te quede más cómodo. También podés pedir un combo por nombre.'},
      {titulo:'Te confirmamos el total',texto:'Te respondemos con el monto y el tiempo estimado de entrega.'},
      {titulo:'Llega a tu puerta',texto:'Pagás al repartidor en efectivo, con tarjeta, Tigo Money, Billetera Personal o Zimple.'}],
    contactoTitulo:'Estamos a la vuelta',
    contactoTexto:'Abrimos todos los días, incluso feriados. Si necesitás algo que no tenemos, lo conseguimos.',
    whatsapp:'0975 480 219', telefono:'',
    direccion:'Cnel. Romero esq. Tte. Rojas Silva', ciudad:'Lambaré',
    horario:'Todos los días 7:00–21:00',
    instagram:'despensadonania', email:'',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Lambare+Paraguay',
    pago:'Efectivo, tarjetas, Tigo Money, Billetera Personal y Zimple',
  }
},
{
  id:'profesionales', rubro:'Servicios profesionales', sub:'Estudio contable · Jurídico', ini:'Pr',
  secciones:['nav','heroTipo','tiras','precios','pasos','testimonios','faq','contacto','pie'],
  d:{
    _accent:'#1E3A5F', _bg:'#F4F5F2', _fg:'#12171D', _font:'editorial', _cardStyle:'grid',
    marca:'Estudio Ayala & Asociados', navCta:'Agendar reunión',
    navLinks:[{txt:'Servicios',url:'#precios'},{txt:'Preguntas',url:'#preguntas'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Contable, impositivo y laboral',
    heroTitulo:'Tu contabilidad al día y tus impuestos presentados a tiempo',
    heroTexto:'Atendemos unipersonales, SRL y SA. Liquidación de IVA e IRE, marangatu, planillas del MTESS y aportes al IPS, con un responsable asignado que conocés por nombre.',
    heroCta:'Ver servicios y honorarios', heroCtaUrl:'#precios', heroImg:'',
    tiras:[{valor:'130+',etiqueta:'Empresas asesoradas'},{valor:'0',etiqueta:'Multas por presentación tardía'},
           {valor:'48 h',etiqueta:'Respuesta a consultas'},{valor:'Marangatu',etiqueta:'Gestión integral'}],
    preciosTitulo:'Servicios y honorarios',
    preciosIntro:'Honorarios mensuales según volumen de comprobantes. La primera reunión de diagnóstico no se cobra.',
    precios:[
      {seccion:'Contabilidad',nombre:'Unipersonal / pequeño contribuyente',detalle:'Hasta 50 comprobantes por mes',precio:'desde Gs. 650.000/mes'},
      {seccion:'Contabilidad',nombre:'SRL o SA',detalle:'Balance, libros y estados contables',precio:'desde Gs. 1.800.000/mes'},
      {seccion:'Impuestos',nombre:'Liquidación de IVA',detalle:'Mensual, con presentación en Marangatu',precio:'Incluido'},
      {seccion:'Impuestos',nombre:'IRE anual y anticipos',detalle:'Cálculo, presentación y seguimiento',precio:'Incluido'},
      {seccion:'Laboral',nombre:'Planilla de sueldos y aportes IPS',detalle:'Por empleado, por mes',precio:'Gs. 70.000'},
      {seccion:'Laboral',nombre:'Registro obrero patronal (MTESS)',detalle:'Alta y actualizaciones',precio:'Gs. 450.000'},
      {seccion:'Trámites',nombre:'Constitución de SRL',detalle:'Escritura, RUC, patente y habilitaciones',precio:'desde Gs. 5.500.000'},
      {seccion:'Trámites',nombre:'Inscripción de RUC unipersonal',detalle:'Con timbrado y talonario',precio:'Gs. 900.000'}],
    pasosTitulo:'Cómo empezamos',
    pasos:[
      {titulo:'Diagnóstico',texto:'Una reunión de una hora, sin costo, para ver en qué estado está tu situación fiscal.'},
      {titulo:'Regularización',texto:'Si hay presentaciones atrasadas o deudas, armamos un plan con plazos y montos.'},
      {titulo:'Puesta al día',texto:'Cargamos tu historial y dejamos todo presentado y conciliado.'},
      {titulo:'Mes a mes',texto:'Recibís un informe mensual con lo presentado, lo que pagaste y lo que viene el mes próximo.'}],
    testiTitulo:'Clientes',
    testimonios:[
      {texto:'Llegué con dos años de IVA sin presentar y una deuda que me daba miedo mirar. En cuatro meses estaba todo regularizado con facilidades de pago.',autor:'Comercio mayorista, Ciudad del Este'},
      {texto:'Lo que más valoro es que me avisan antes del vencimiento, no después. Nunca más pagué una multa.',autor:'Empresa de servicios, Asunción'}],
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿Atienden empresas del interior?',r:'Sí. Trabajamos con clientes de Ciudad del Este, Encarnación y Pedro Juan Caballero de forma remota. Los documentos se envían escaneados.'},
      {p:'¿Qué pasa si tengo deudas con la SET?',r:'Se puede gestionar un plan de facilidades de pago. Calculamos el monto real con intereses y presentamos la solicitud.'},
      {p:'¿Incluye el timbrado y las facturas?',r:'Gestionamos el timbrado ante la SET. La impresión del talonario la hace una imprenta habilitada y se factura aparte.'}],
    contactoTitulo:'Primera reunión sin costo',
    contactoTexto:'Contanos qué tipo de contribuyente sos y desde cuándo. Coordinamos una reunión presencial o por videollamada.',
    whatsapp:'0981 606 442', telefono:'021 445 909',
    direccion:'Estrella 765, piso 4, oficina 42', ciudad:'Asunción',
    horario:'Lun a vie 8:00–17:00',
    instagram:'ayala.estudio', email:'consultas@ayalaasociados.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Estrella+765+Asuncion',
    pago:'Transferencia bancaria y débito automático mensual',
  }
},
);

RUBROS.push(
{
  id:'educacion', rubro:'Educación', sub:'Instituto · Academia · Cursos', ini:'Ed',
  secciones:['nav','heroSplit','tiras','cards','pasos','faq','testimonios','contacto','pie'],
  d:{
    _accent:'#4438C4', _bg:'#F3F3FB', _fg:'#14132A', _font:'moderna', _cardStyle:'grid',
    marca:'Instituto Mbo’ehao', navCta:'Inscribirme',
    navLinks:[{txt:'Cursos',url:'#catalogo'},{txt:'Inscripción',url:'#preguntas'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Inscripciones abiertas · Marzo 2026',
    heroTitulo:'Cursos cortos que terminan en un certificado que sirve',
    heroTexto:'Idiomas, informática y oficios digitales con clases presenciales en Asunción y online para todo el país. Grupos de hasta 12 personas.',
    heroCta:'Ver cursos', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'12',etiqueta:'Máximo por grupo'},{valor:'MEC',etiqueta:'Certificado reconocido'},
           {valor:'Gs. 280.000',etiqueta:'Cuota mensual desde'},{valor:'Online',etiqueta:'Clases en vivo, no grabadas'}],
    cardsTitulo:'Cursos de este cuatrimestre',
    cardsIntro:'Todos los cursos incluyen material digital y certificado al finalizar. Cupos limitados por grupo.',
    cards:[
      {titulo:'Inglés conversacional',meta:'4 meses · Gs. 320.000/mes',texto:'Niveles A1 a B2. Dos clases por semana de 90 minutos, con profesor titulado.',img:''},
      {titulo:'Portugués para el comercio',meta:'3 meses · Gs. 300.000/mes',texto:'Orientado a atención a brasileños: vocabulario comercial, negociación y facturación.',img:''},
      {titulo:'Excel desde cero a avanzado',meta:'2 meses · Gs. 280.000/mes',texto:'Tablas dinámicas, BUSCARV, gráficos y automatización básica. Con computadoras en sala.',img:''},
      {titulo:'Marketing digital',meta:'3 meses · Gs. 380.000/mes',texto:'Instagram, WhatsApp Business y pauta paga. Trabajás sobre tu propio emprendimiento.',img:''},
      {titulo:'Programación web inicial',meta:'5 meses · Gs. 450.000/mes',texto:'HTML, CSS y JavaScript. Terminás con tres proyectos publicados en internet.',img:''},
      {titulo:'Guaraní para profesionales',meta:'3 meses · Gs. 260.000/mes',texto:'Atención al público en guaraní para salud, comercio y sector público.',img:''}],
    pasosTitulo:'Cómo inscribirte',
    pasos:[
      {titulo:'Elegís el curso',texto:'Escribinos y te contamos días, horarios y qué nivel te conviene.'},
      {titulo:'Prueba de nivel',texto:'Para idiomas, una evaluación corta y gratuita para ubicarte en el grupo correcto.'},
      {titulo:'Matrícula',texto:'Se abona la matrícula y la primera cuota. Cédula y una foto tipo carnet.'},
      {titulo:'Empezás',texto:'Recibís el material y el enlace del grupo. Las clases arrancan el primer lunes del mes.'}],
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿El certificado sirve para presentar en un trabajo?',r:'Sí. Los certificados están registrados ante el MEC e incluyen carga horaria y contenidos. Se entregan en papel y en PDF.'},
      {p:'¿Puedo cambiar de horario a mitad de curso?',r:'Sí, si hay cupo en otro grupo del mismo nivel. Se pide una semana de anticipación.'},
      {p:'¿Las clases online son grabadas?',r:'No. Son en vivo con el mismo profesor y el mismo grupo. Si faltás, te mandamos la grabación de esa clase.'}],
    testiTitulo:'Egresados',
    testimonios:[
      {texto:'Hice portugués porque atiendo turistas brasileños en el local. A los dos meses ya cerraba ventas sin usar el traductor.',autor:'Comerciante, Ciudad del Este'},
      {texto:'Entré a Excel sabiendo prender la computadora, nada más. Salí armando las planillas de stock de la empresa donde trabajo.',autor:'Egresada 2025, Capiatá'}],
    contactoTitulo:'Consultá por tu curso',
    contactoTexto:'Decinos qué querés estudiar y si preferís presencial u online. Te mandamos horarios y cupos disponibles.',
    whatsapp:'0984 227 601', telefono:'021 490 228',
    direccion:'Herrera 1180 c/ Brasil', ciudad:'Asunción',
    horario:'Lun a vie 8:00–20:00 · Sáb 8:00–12:00',
    instagram:'instituto.mboehao', email:'inscripciones@mboehao.edu.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Herrera+1180+Asuncion',
    pago:'Efectivo, tarjetas, transferencia, Tigo Money y Zimple',
  }
},
{
  id:'tecnologia', rubro:'Tecnología', sub:'Celulares · Servicio técnico · Informática', ini:'Te',
  secciones:['nav','heroBanner','tiras','cards','precios','faq','contacto','pie'],
  d:{
    _accent:'#DB4F97', _bg:'#15141C', _fg:'#EDEAF2', _font:'suave', _cardStyle:'compacto',
    marca:'TecnoEste', navCta:'Consultar stock',
    navLinks:[{txt:'Productos',url:'#catalogo'},{txt:'Reparaciones',url:'#precios'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Importación directa desde Ciudad del Este',
    heroTitulo:'Celulares, notebooks y servicio técnico con garantía escrita',
    heroTexto:'Equipos nuevos y sellados con boleta y garantía de 12 meses. Reparación de pantallas, baterías y placas con repuestos originales. Envíos a todo el país.',
    heroCta:'Ver productos', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'12 meses',etiqueta:'Garantía escrita'},{valor:'24 a 48 h',etiqueta:'Reparaciones comunes'},
           {valor:'Envío nacional',etiqueta:'Encomiendas y courier'},{valor:'6 cuotas',etiqueta:'Sin interés con tarjeta'}],
    cardsTitulo:'Lo que tenemos en stock',
    cardsIntro:'El stock rota rápido: confirmá disponibilidad y precio del día por WhatsApp antes de venir.',
    cards:[
      {titulo:'Celulares gama media',meta:'desde Gs. 1.450.000',texto:'Equipos nuevos, libres de fábrica, con boleta. Varias marcas y capacidades.',img:''},
      {titulo:'Celulares gama alta',meta:'desde Gs. 4.900.000',texto:'Últimos modelos sellados. Consultá por disponibilidad de color y memoria.',img:''},
      {titulo:'Notebooks',meta:'desde Gs. 3.200.000',texto:'Para oficina y estudio. Instalamos el sistema y el paquete de oficina sin cargo.',img:''},
      {titulo:'Accesorios',meta:'Cargadores, fundas, audífonos',texto:'Cables certificados, power banks y protectores de pantalla colocados en el local.',img:''}],
    preciosTitulo:'Servicio técnico',
    preciosIntro:'Diagnóstico sin costo. Si no tiene arreglo, no se cobra nada.',
    precios:[
      {seccion:'Celulares',nombre:'Cambio de pantalla',detalle:'Según modelo · 24 a 48 h',precio:'desde Gs. 420.000'},
      {seccion:'Celulares',nombre:'Cambio de batería',detalle:'Original o compatible certificada',precio:'desde Gs. 250.000'},
      {seccion:'Celulares',nombre:'Cambio de pin de carga',detalle:'Mismo día en la mayoría de los modelos',precio:'desde Gs. 180.000'},
      {seccion:'Celulares',nombre:'Recuperación por mojadura',detalle:'Limpieza de placa por ultrasonido',precio:'desde Gs. 300.000'},
      {seccion:'Computadoras',nombre:'Formateo e instalación',detalle:'Con respaldo de tus archivos',precio:'Gs. 200.000'},
      {seccion:'Computadoras',nombre:'Cambio a disco sólido (SSD)',detalle:'Mano de obra, disco aparte',precio:'Gs. 180.000'},
      {seccion:'Computadoras',nombre:'Limpieza y cambio de pasta térmica',detalle:'Para notebooks que se recalientan',precio:'Gs. 220.000'}],
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿La garantía cubre pantalla rota?',r:'No. La garantía de 12 meses cubre fallas de fábrica. Los golpes, mojaduras y roturas quedan fuera, pero los reparamos con precio de cliente.'},
      {p:'¿Hacen envíos al interior?',r:'Sí, por encomienda o courier. Enviamos el mismo día si el pago se confirma antes de las 15:00. El flete lo paga el comprador.'},
      {p:'¿Los equipos son homologados para Paraguay?',r:'Sí. Todos los celulares que vendemos funcionan con Tigo, Personal, Claro y Vox, y vienen con boleta legal.'}],
    contactoTitulo:'Consultá stock y precios',
    contactoTexto:'Los precios cambian con la cotización del dólar. Escribinos y te pasamos el valor del día.',
    whatsapp:'0972 885 340', telefono:'061 500 772',
    direccion:'Av. San Blas 890, Shopping Vendôme, local 24', ciudad:'Ciudad del Este',
    horario:'Lun a sáb 8:00–18:00 · Dom cerrado',
    instagram:'tecnoeste.py', email:'ventas@tecnoeste.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Ciudad+del+Este+Paraguay',
    pago:'Efectivo (Gs. o USD), tarjetas hasta 6 cuotas, transferencia y Tigo Money',
  }
},
{
  id:'eventos', rubro:'Eventos', sub:'Salón de fiestas · Organización', ini:'Ev',
  secciones:['nav','heroBanner','tiras','cards','precios','pasos','testimonios','contacto','pie'],
  d:{
    _accent:'#9A7B1F', _bg:'#12100E', _fg:'#F2EDE2', _font:'editorial', _cardStyle:'grid',
    marca:'Salón Kuarahy', navCta:'Consultar fecha',
    navLinks:[{txt:'Paquetes',url:'#catalogo'},{txt:'Precios',url:'#precios'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Bodas · Quince años · Eventos de empresa',
    heroTitulo:'Un salón para 300 personas y un equipo que ya hizo 400 fiestas',
    heroTexto:'Salón climatizado con jardín, cocina industrial, estacionamiento propio y generador. Trabajamos con paquete cerrado o solo alquiler.',
    heroCta:'Ver paquetes', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'300',etiqueta:'Personas sentadas'},{valor:'400+',etiqueta:'Eventos realizados'},
           {valor:'80 autos',etiqueta:'Estacionamiento propio'},{valor:'Generador',etiqueta:'Sin cortes de luz'}],
    cardsTitulo:'Paquetes',
    cardsIntro:'Todos incluyen salón climatizado, mobiliario, mantelería, personal de limpieza y seguridad.',
    cards:[
      {titulo:'Paquete Esencial',meta:'desde Gs. 18.000.000',texto:'Salón por 8 horas, mobiliario, mantelería, sonido básico e iluminación. Hasta 150 personas.',img:''},
      {titulo:'Paquete Completo',meta:'desde Gs. 34.000.000',texto:'Todo lo anterior más catering de tres tiempos, barra libre sin alcohol, DJ y decoración floral. Hasta 250 personas.',img:''},
      {titulo:'Paquete Empresa',meta:'desde Gs. 12.000.000',texto:'Montaje tipo conferencia o cóctel, proyector, pantalla, micrófonos y coffee break. Hasta 200 personas.',img:''},
      {titulo:'Solo alquiler del salón',meta:'desde Gs. 9.500.000',texto:'Traés tu propio catering y proveedores. Incluye mobiliario, limpieza y seguridad.',img:''}],
    preciosTitulo:'Adicionales',
    preciosIntro:'Se contratan sobre cualquier paquete. Los precios son para eventos de hasta 250 personas.',
    precios:[
      {seccion:'Gastronomía',nombre:'Barra libre con alcohol',detalle:'Cinco horas, por persona',precio:'Gs. 95.000'},
      {seccion:'Gastronomía',nombre:'Mesa de dulces',detalle:'Ocho variedades',precio:'Gs. 3.200.000'},
      {seccion:'Gastronomía',nombre:'Torta de bodas o quince',detalle:'Tres pisos, diseño a elección',precio:'desde Gs. 1.800.000'},
      {seccion:'Producción',nombre:'Hora extra de salón',detalle:'Después de las 8 horas contratadas',precio:'Gs. 1.500.000'},
      {seccion:'Producción',nombre:'Pantalla LED y video',detalle:'Con operador toda la noche',precio:'Gs. 4.500.000'},
      {seccion:'Producción',nombre:'Fotografía y video',detalle:'Dos fotógrafos y un camarógrafo',precio:'desde Gs. 5.500.000'},
      {seccion:'Producción',nombre:'Show de fuegos fríos',detalle:'Entrada de la torta',precio:'Gs. 900.000'}],
    pasosTitulo:'Cómo reservar la fecha',
    pasos:[
      {titulo:'Consultá disponibilidad',texto:'Las fechas de noviembre a marzo se reservan con seis meses de anticipación.'},
      {titulo:'Visitá el salón',texto:'Coordinamos una visita, preferentemente un día que haya montaje armado.'},
      {titulo:'Seña del 30%',texto:'Con la seña la fecha queda bloqueada y el precio congelado, aunque falten meses.'},
      {titulo:'Reunión de producción',texto:'Un mes antes definimos menú, montaje, horarios y lista de proveedores externos.'}],
    testiTitulo:'Familias y empresas que confiaron',
    testimonios:[
      {texto:'Se cortó la luz en todo el barrio a las once de la noche y en el salón nadie se dio cuenta. El generador arrancó solo.',autor:'Boda de 220 invitados, octubre 2025'},
      {texto:'Organizaron la cena de fin de año de la empresa en tres semanas. Todo salió como lo planeamos.',autor:'Gerente de RR. HH., empresa importadora'}],
    contactoTitulo:'Consultá tu fecha',
    contactoTexto:'Decinos la fecha, la cantidad aproximada de invitados y el tipo de evento. Te respondemos con disponibilidad y presupuesto.',
    whatsapp:'0986 310 475', telefono:'021 288 690',
    direccion:'Ruta Luque–San Bernardino km 18', ciudad:'Luque',
    horario:'Visitas: lun a sáb 9:00–18:00 con cita previa',
    instagram:'salonkuarahy', email:'eventos@salonkuarahy.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Luque+Paraguay',
    pago:'Seña del 30% y saldo hasta 7 días antes del evento. Transferencia o tarjeta.',
  }
},
{
  id:'turismo', rubro:'Turismo y hotelería', sub:'Hotel · Posada · Excursiones', ini:'Tu',
  secciones:['nav','heroBanner','tiras','cards','precios','texto','faq','contacto','pie'],
  d:{
    _accent:'#0F7F9E', _bg:'#F2F8FA', _fg:'#0E1E24', _font:'suave', _cardStyle:'ancho',
    marca:'Posada Yvytu', navCta:'Reservar',
    navLinks:[{txt:'Habitaciones',url:'#catalogo'},{txt:'Excursiones',url:'#precios'},{txt:'Contacto',url:'#contacto'}],
    heroEyebrow:'Encarnación · a 10 minutos de la costanera',
    heroTitulo:'Dormir cerca del río, despertar con desayuno casero',
    heroTexto:'Doce habitaciones con aire acondicionado, piscina, desayuno incluido y estacionamiento cerrado. Organizamos excursiones a las Ruinas Jesuíticas y al Carnaval.',
    heroCta:'Ver habitaciones', heroCtaUrl:'#catalogo', heroImg:'',
    tiras:[{valor:'12',etiqueta:'Habitaciones'},{valor:'10 min',etiqueta:'De la costanera'},
           {valor:'Incluido',etiqueta:'Desayuno casero'},{valor:'Cerrado',etiqueta:'Estacionamiento propio'}],
    cardsTitulo:'Habitaciones',
    cardsIntro:'Precios por noche, desayuno e impuestos incluidos. En temporada de Carnaval rigen tarifas especiales.',
    cards:[
      {titulo:'Habitación doble',meta:'Gs. 320.000/noche',
       texto:'Cama matrimonial o dos individuales, baño privado, aire acondicionado, wifi y frigobar. Vista al jardín.',img:''},
      {titulo:'Habitación familiar',meta:'Gs. 480.000/noche',
       texto:'Hasta cuatro personas: una matrimonial y dos individuales. Baño privado y mesa de trabajo.',img:''},
      {titulo:'Suite con balcón',meta:'Gs. 620.000/noche',
       texto:'Habitación amplia con balcón sobre la piscina, sofá, escritorio y bañera.',img:''}],
    preciosTitulo:'Excursiones y servicios',
    preciosIntro:'Salidas con guía habilitado. Mínimo dos personas, se coordinan con un día de anticipación.',
    precios:[
      {seccion:'Excursiones',nombre:'Ruinas Jesuíticas de Trinidad y Jesús',detalle:'Medio día, con guía y traslado',precio:'Gs. 280.000 por persona'},
      {seccion:'Excursiones',nombre:'Circuito de Colonias Alemanas',detalle:'Día completo, con almuerzo',precio:'Gs. 420.000 por persona'},
      {seccion:'Excursiones',nombre:'Costanera y playa San José',detalle:'Traslado ida y vuelta',precio:'Gs. 90.000 por persona'},
      {seccion:'Servicios',nombre:'Traslado desde la terminal',detalle:'Hasta cuatro pasajeros',precio:'Gs. 80.000'},
      {seccion:'Servicios',nombre:'Traslado desde Posadas (Argentina)',detalle:'Cruce de frontera incluido',precio:'Gs. 250.000'},
      {seccion:'Servicios',nombre:'Almuerzo en la posada',detalle:'Menú del día, por persona',precio:'Gs. 65.000'},
      {seccion:'Servicios',nombre:'Lavandería',detalle:'Por kilo, entrega en 24 h',precio:'Gs. 25.000'}],
    textoTitulo:'Una casa de familia que se volvió posada',
    textoCuerpo:'La casa es de mi abuela y tiene setenta años. En 2017 la reformamos habitación por habitación, sin tocar los pisos originales ni el aljibe del patio.\n\nEl desayuno lo hace mi mamá: chipa recién horneada, mbeju, frutas de estación y cocido quemado a la manera de acá. Se sirve de 7 a 10, y si venís del Carnaval a las seis de la mañana, te lo guardamos.',
    textoImg:'',
    faqTitulo:'Preguntas frecuentes',
    faq:[
      {p:'¿Se puede pagar en pesos argentinos o reales?',r:'Sí, aceptamos pesos argentinos, reales y dólares al cambio del día. También transferencia bancaria en guaraníes.'},
      {p:'¿Aceptan mascotas?',r:'Sí, mascotas de hasta 15 kg sin cargo adicional. Avisanos al reservar para asignarte una habitación de planta baja.'},
      {p:'¿Cómo son las tarifas de Carnaval?',r:'Durante las noches de Carnaval (enero y febrero) rige una tarifa especial con mínimo de tres noches. Consultanos con anticipación: se llena rápido.'}],
    contactoTitulo:'Reservá tu estadía',
    contactoTexto:'Contanos fechas, cantidad de personas y si necesitás traslado desde la terminal o la frontera.',
    whatsapp:'0985 774 102', telefono:'071 204 588',
    direccion:'Villarrica 1420 c/ Curupayty', ciudad:'Encarnación',
    horario:'Recepción 24 horas · Check-in 14:00 · Check-out 10:00',
    instagram:'posadayvytu', email:'reservas@posadayvytu.com.py',
    mapaUrl:'https://www.google.com/maps/search/?api=1&query=Encarnacion+Paraguay',
    pago:'Guaraníes, dólares, reales y pesos argentinos. Tarjetas y transferencia.',
  }
},
);
